# Website info
title: UZPG
bio: Developer & Designer
blog_description: This is a blog about webdev, computer science and opensource. I’ll be writing about all the interesting technology that powers our world and how it can make us think and create new things.
#email: 
# image paths
# you can create your avatar at https://getavataaars.com/
avatar: /assets/images/avatar.svg

# optional about image
about_image: /assets/images/about.png
#logo: /assets/images/logo.png   # if you have one

social_links:
  #twitter: user
  github: Uzay-G
  #facebook: user
  twitter: EtherealUnagi
  linkedin: uzay-girit-a208161a2
  #dribbble: user
    # flickr:   user
    # instagram: user
    # pinterest: user
    # youtube: user

# you can set a "google_analytics" tracking id value and your analytics will be set up

# you can also set your "disqus_shortname" which will enable disqus comments on your site

date_format: "%b %-d, %Y"
plugins:
  - jekyll-seo-tag

collections:
  projects:
    sort_by: value
    output: true
  categories:
    output: true
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "category"
