# Website info
title: Pragmatic
bio: 'Minimal jekyll theme for bloggers'
#email: 
# avatar image and about image
# you can create your avatar at https://getavataaars.com/
avatar: /assets/images/avataar.svg
about_image: /assets/images/about.png
logo: /assets/images/logo.png   # if you have one
# tinyletter newsletter if you have one
#tinyletter:
social_links:
  twitter: user
  github:  user
  facebook: user
  github: user
  linkedin: user
  dribbble: user
    # flickr:   user
    # instagram: user
    # pinterest: user
    # youtube: user

# you can set a "google_analytics" tracking id value and your analytics will be set up

# you can also set your "disqus_shortname" which will enable disqus comments on your site

date_format: "%b %-d, %Y"
plugins:
  - jekyll-seo-tag

collections:
  projects:
    sort_by: value
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"